name: Set Mysql And CI

on:
  push:
    branches: ["be-test"]
  workflow_dispatch:

jobs:
  setup-mysql-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Connect and fetch data from MySQL
        run: |
          mysql -h127.0.0.1 -uroot -prootpassword -e "source backend/database/init.sql;"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set yml file for database connection
        uses: microsoft/variable-substitution@v1
        with:
          files: "./backend/src/main/resources/application.yml"
        env:
          spring.datasource.url: jdbc:mysql://localhost:3306/88hey-test
          spring.datasource.username: root
          spring.datasource.password: rootpassword

      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew

      - name: Run tests with Gradle
        run: ./backend/gradlew test
